//CLIENTS ACTIONS
export const CLIENT_JOIN = "CLIENT_JOIN";
export const CLIENT_UPDATE_USERNAME = "CLIENT_UPDATE_USERNAME";
export const CLIENT_UPDATE_DISPLAY_CLOCK = "CLIENT_UPDATE_DISPLAY_CLOCK";
export const CLIENT_SEND_BY_SHORTCUT = "CLIENT_SEND_BY_SHORTCUT";
export const CLIENT_UPDATE_LANG = "CLIENT_UPDATE_LANG";
export const CLIENT_RESET_TO_DEFAULT = "CLIENT_RESET_TO_DEFAULT";

//Users Actions
