//CLIENTS ACTIONS
export const CLIENT_JOIN = "CLIENT_JOIN";
export const CLIENT_UPDATE_USERNAME = "CLIENT_UPDATE_USERNAME";
export const CLIENT_UPDATE_DISPLAY_CLOCK = "CLIENT_UPDATE_DISPLAY_CLOCK";
export const CLIENT_SEND_BY_SHORTCUT = "CLIENT_SEND_BY_SHORTCUT";
export const CLIENT_UPDATE_LANG = "CLIENT_UPDATE_LANG";
export const CLIENT_RESET_TO_DEFAULT = "CLIENT_RESET_TO_DEFAULT";
export const CLIENT_UPDATE_THEME = "CLIENT_UPDATE_THEME";

//Users Actions
export const USERS_NEW_USER_JOIN = "USERS_NEW_USER_JOIN";
export const USERS_USER_DISCONNECT = "USERS_USER_DISCONNECT";
export const USERS_USER_CHANGE_USERNAME = "USERS_USER_CHANGE_USERNAME";
export const USERS_SET_USERS_LIST = "USERS_SET_USERS_LIST";

//Tabs
export const CHANGE_TAB = "CHANGE_TAB";

//new unread message
export const NEW_UNREAD_MESSAGES_INCREMENT = "NEW_UNREAD_MESSAGES_INCREMENT";
export const NEW_UNREAD_MESSAGES_RESET = "NEW_UNREAD_MESSAGES_RESET";

//MESSAGES
export const MESSAGES_NEW_MESSAGE = "MESSAGES_NEW_MESSAGE";
